import { StyleSheet } from 'react-native';
import { colors } from '../../utils/Colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bgColor },
  header: {
    overflow: 'hidden',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    backgroundColor: colors.goldLight,
    paddingBottom: 18,
  },
  headerGear: { top: -45, right: -35 },
  headerTitle: { marginTop: 14, marginHorizontal: 20 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 120 },
  // room for the floating tab bar
  listContent: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 140 },
  empty: { marginTop: 30, paddingHorizontal: 20 },

  section: { marginBottom: 20 },

  avatar: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: colors.goldSoft,
  },
  avatarLight: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.45)',
  },

  bar: { height: 6, borderRadius: 3, overflow: 'hidden', width: '100%' },
  barFill: { height: '100%', borderRadius: 3 },

  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },

  topCard: {
    borderRadius: 18,
    overflow: 'hidden',
    padding: 14,
    backgroundColor: '#A8740F',
  },
  topGear: { top: -40, right: -30 },
  topRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  topAvatarRing: {
    padding: 2,
    borderRadius: 31,
    borderWidth: 2,
    borderColor: colors.goldLight,
  },
  topRankBadge: {
    position: 'absolute',
    right: -4,
    bottom: -2,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.goldLight,
    borderWidth: 1.5,
    borderColor: '#8A5A0E',
  },
  topInfo: { flex: 1, gap: 2 },
  topScore: { alignItems: 'flex-end', width: 76 },
  topScoreRow: { flexDirection: 'row', alignItems: 'flex-end' },
  topOutOf: { marginBottom: 5, marginLeft: 2 },
  topBarWrap: { width: '100%', marginTop: 4 },
  topParams: {
    flexDirection: 'row',
    marginTop: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.16)',
  },
  topParam: { flex: 1, minWidth: 0, alignItems: 'center', gap: 2 },
  topParamDivider: { borderLeftWidth: 1, borderLeftColor: 'rgba(255,255,255,0.18)' },
  topParamValue: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  topParamDot: { width: 7, height: 7, borderRadius: 4 },

  // full-bleed ticker (cancels the list's side padding)
  zoneScroll: { marginHorizontal: -16, overflow: 'hidden' },
  tickerTrack: { flexDirection: 'row', paddingLeft: 16 },
  // each set ends with the same gap as between cards, so the copy lines up seamlessly
  tickerSet: { flexDirection: 'row', gap: 10, paddingRight: 10, paddingTop: 2, paddingBottom: 10 },
  zoneCard: {
    width: 200,
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 12,
    overflow: 'hidden',
  },
  zoneAccent: { position: 'absolute', top: 0, left: 0, right: 0, height: 3 },
  zoneHead: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  zoneGroup: { flex: 1, letterSpacing: 0.4 },
  zoneBody: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  zoneInfo: { flex: 1, gap: 1 },
  zoneScoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    marginBottom: 6,
  },
  zoneScore: { flexDirection: 'row', alignItems: 'flex-end' },
  zoneOutOf: { marginBottom: 3, marginLeft: 2 },
  zoneTag: { borderRadius: 6, paddingHorizontal: 6, paddingVertical: 3 },

  listHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  asmChip: {
    backgroundColor: '#8A5A0E',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  listSub: { marginTop: 6 },
  search: {
    marginTop: 12,
    marginBottom: 14,
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EDE6D3',
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: '#202432',
  },

  card: {
    backgroundColor: colors.white,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
    marginBottom: 14,
  },
  cardPressed: { opacity: 0.85, transform: [{ scale: 0.99 }] },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  rank: {
    minWidth: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.goldSoft,
    paddingHorizontal: 4,
  },
  cardTitle: { flex: 1, gap: 2 },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  divider: { height: 1, backgroundColor: '#EFEAE0', marginVertical: 12 },
  params: { flexDirection: 'row' },
  param: { flex: 1, gap: 3 },
});
